version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app/
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - go-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=mysql'
      - 'PMA_PORT=3306'

volumes:
  go-mysql-data: